### ISSUE TITLE
Device drop down menu won't work; a vertical scroll is displayed instead

### ISSUE THREAD

**Issue by guillaumelamirand** [custom-cards/spotify-card#28]
Hello;

First of all, thank you for your card.
Unfortunately, I have an issue with it. I am using Opera 63.0.3368.94 and the dropdown menu used to select the spotify devices doesn't work as it should do.

When I try to change the current device, the menu shows up bellow but a vertical scroll bar appears on the right (see screenshots bellow). It looks like the dropdown is not a html one but more a div with display:none which could cause the issue.

Let me know if you need more details.
Regards

![0](https://user-images.githubusercontent.com/4324887/65582667-24ee9680-df7e-11e9-97c4-987f96a770fa.png)
![1](https://user-images.githubusercontent.com/4324887/65582674-26b85a00-df7e-11e9-828d-a79e185626cc.png)

**Comment by fondberg** [comment]
Do you use any custom cards or controls around the spotify card?

**Comment by lamirand-g** [comment]
Yes I do. I use a conditional card to hid/display the spotify card according media player status,and I have a custom mini media player on the left.

Do you think those have an impact?

**Comment by fondberg** [comment]
I'm afraid so. Try without and let me know if it works

**Comment by fondberg** [comment]
I have now released v1.10 which should has a new property to set the height if the card in pixels.Can you try with this one?

**Comment by coenboomkamp** [comment]
Scrollbar is still shown in v1.10. Changing the following css does the trick for me:

.playlists {
    overflow-y: scroll;
}
.dropdown {
    position: absolute;
}

**Comment by fondberg** [comment]
Can you make a PR?

**Comment by coenboomkamp** [comment]
Sure if you give me permissions.

**Comment by fondberg** [comment]
You don't need permission to create  PR. Just fork the repo, create a branch and commit and make a pull request (standard procedure for all github repos)

**Comment by TuomasPakkanen** [comment]
Hi,

Facing the same issue. I tried moving the card to another view with no other cards in it, but it doesn't help. Also tried adding the height parameter with plenty of extra room, but that also did not work. @coenboomkamp can you make the PR? I'm not sure where I should make the CSS change to fix the issue. 

![image](https://user-images.githubusercontent.com/7880089/71782010-c5bd0b00-2fdd-11ea-8ab8-b31fb8c9dbcd.png)

**Comment by fondberg** [comment]
I did release a new version which should fix the horizontal scrolling and you should be able to fix the vertical one with the height and limit properties to the card

**Comment by TuomasPakkanen** [comment]
> I did release a new version which should fix the horizontal scrolling and you should be able to fix the vertical one with the height and limit properties to the card

There's no more horizontal scrolling which is great. Still affected by the vertical scrolling though, even with "sufficient" extra space defined with the height property. Scrolling seems to be caused by the media player selection. Otherwise the card seems to work nicely. Not sure if you can somehow show up all Spotify connect devices even though they are not currently playing, but have not played around with this too much yet. Thanks for your help!

![image](https://user-images.githubusercontent.com/7880089/71803366-47a64600-3069-11ea-93c5-530b2faae6f7.png)

**Comment by TuomasPakkanen** [comment]
Update:
Not sure what might have fixed the issue, but now I only see the vertical scrollbar next to the playlists. Not sure if you can do something about that one as well.

**Comment by fondberg** [comment]
Har you set the height parameter?

**Comment by TuomasPakkanen** [comment]
Tried that one. It actually shows up the vertical scrollbar (grayed out) even though there's no need for scrolling:
![image](https://user-images.githubusercontent.com/7880089/72241743-4d170980-35f0-11ea-92cb-68659a83a4ff.png)
