### ISSUE TITLE
Spotcast component error in Android App & Chromium

### ISSUE THREAD

**Issue by jayefjay** [custom-cards/spotify-card#90]
Hi, 

I have beta14 installed and it works without problems in Firefox 78.0.2 (64-Bit) in Windows 10. However, in both the Android App 1.11.0 and on Chromium on the Raspberry 7" touchscreen I get the error message "spotcast integration has to be installed for this component to work". The component is installed.

**Comment by fondberg** [comment]
Can you provide any logs?

**Comment by jayefjay** [comment]
Those seem relevant I think:

______________________
Logger: frontend.js.latest.202007021
Source: components/system_log/__init__.py:209
First occurred: 12:45:18 (23 occurrences)
Last logged: 18:29:54

- http://192.168.178.63:8123/local/community/spotify_card/spotify-card.js:6:0 SyntaxError: expected expression, got '<'
-     http://192.168.178.63:8123/hacsfiles/spotify-card/spotify-card.js:162:0 NotSupportedError: CustomElementRegistry.define: 'spotify-card' has already been defined as a custom element
-     http://192.168.178.63:8123/lovelace/overview:0:0 Uncaught
-     http://192.168.178.63:8123/frontend_latest/chunk.abf8f86ff841c8a02148.js:277:325 Uncaught TypeError: Cannot read property 'removeChild' of null
-----------------------

Logger: homeassistant.components.websocket_api.http.connection.140310983350096
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:36:26 (113 occurrences)
Last logged: 18:29:35
------------------------

**Comment by davidrustingha** [comment]
I have the error too. On Opera Mobile (old Android 4.4.2 tablet)

**Comment by davidrustingha** [comment]
These logs seemed relevant
````
homeassistant.components.websocket_api.http.connection.139880352912592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/spotcast/__init__.py", line 221, in websocket_handle_castdevices
    for k in known_devices
  File "/config/custom_components/spotcast/__init__.py", line 221, in <listcomp>
    for k in known_devices
TypeError: 'set' object is not subscriptable
2020-07-17 19:20:44 DEBUG (SyncWorker_7) [custom_components.spotcast] websocket_handle_devices msg: {'type': 'spotcast/devices', 'id': 116}
2020-07-17 19:20:44 DEBUG (SyncWorker_7) [custom_components.spotcast] setting up with  account default
2020-07-17 19:20:44 DEBUG (SyncWorker_7) [custom_components.spotcast] expires: 1595009615 time: 1595006444.648478
2020-07-17 19:20:44 DEBUG (SyncWorker_0) [custom_components.spotcast] websocket_handle_player msg: {'type': 'spotcast/player', 'id': 117}
2020-07-17 19:20:44 DEBUG (SyncWorker_0) [custom_components.spotcast] setting up with  account default
2020-07-17 19:20:44 DEBUG (SyncWorker_0) [custom_components.spotcast] expires: 1595009615 time: 1595006444.8108354
2020-07-17 19:20:44 DEBUG (MainThread) [custom_components.spotcast] websocket_handle_castdevices msg: {'type': 'spotcast/castdevices', 'id': 118}
2020-07-17 19:20:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139880352912592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/spotcast/__init__.py", line 221, in websocket_handle_castdevices
    for k in known_devices
  File "/config/custom_components/spotcast/__init__.py", line 221, in <listcomp>
    for k in known_devices
TypeError: 'set' object is not subscriptable
2020-07-17 19:21:02 DEBUG (SyncWorker_2) [custom_components.spotcast] websocket_handle_devices msg: {'type': 'spotcast/devices', 'id': 119}
2020-07-17 19:21:02 DEBUG (SyncWorker_2) [custom_components.spotcast] setting up with  account default
2020-07-17 19:21:02 DEBUG (SyncWorker_2) [custom_components.spotcast] expires: 1595009615 time: 1595006462.8852196
2020-07-17 19:21:03 DEBUG (SyncWorker_7) [custom_components.spotcast] websocket_handle_player msg: {'type': 'spotcast/player', 'id': 120}
2020-07-17 19:21:03 DEBUG (SyncWorker_7) [custom_components.spotcast] setting up with  account default
2020-07-17 19:21:03 DEBUG (SyncWorker_7) [custom_components.spotcast] expires: 1595009615 time: 1595006463.069619
2020-07-17 19:21:03 DEBUG (MainThread) [custom_components.spotcast] websocket_handle_castdevices msg: {'type': 'spotcast/castdevices', 'id': 121}
2020-07-17 19:21:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139880352912592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/spotcast/__init__.py", line 221, in websocket_handle_castdevices
    for k in known_devices
  File "/config/custom_components/spotcast/__init__.py", line 221, in <listcomp>
    for k in known_devices
TypeError: 'set' object is not subscriptable
````

**Comment by fondberg** [comment]
I fixed that in spotcast 3.3.4, for the rest I don't know ATM. I tested with my raspberry and chromium with the latest of both the card and spotcast and it works

**Comment by jayefjay** [comment]
I updated to spotcast 3.3.4, I am still having the same problem unfortunately, still getting "Received invalid command: spotcast/devices"

` Log Details (ERROR)

Logger: homeassistant.components.websocket_api.http.connection.140024823499792
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:55:34 (8 occurrences)
Last logged: 20:58:41 `

` Log Details (ERROR)

Logger: homeassistant.components.websocket_api.http.connection.140024893137232
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:54:19 (87 occurrences)
Last logged: 20:58:41 `

` Log Details (ERROR)

Logger: frontend.js.latest.202007021
Source: components/system_log/__init__.py:209
First occurred: 20:55:32 (2 occurrences)
Last logged: 20:56:49 `

**Comment by fondberg** [comment]
Can you paste the spotcast logs from home assiatant

**Comment by jayefjay** [comment]
Do you mean those?

2020-07-18 06:41:21 ERROR (MainThread) [frontend.js.latest.202007021] http://192.168.178.63:8123/hacsfiles/spotify-card/spotify-card.js:103:0 NotSupportedError: CustomElementRegistry.de                                               fine: 'spotify-card' has already been defined as a custom element
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices
2020-07-18 06:42:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140409282509712] Received invalid command: spotcast/devices

**Comment by jayefjay** [comment]
Ok, I set the logging to debug. Now I have more:

`
2020-07-18 08:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received invalid command: spotcast/devices
2020-07-18 08:37:21 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received {'type': 'spotcast/devices', 'id': 4890}
2020-07-18 08:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received invalid command: spotcast/devices
2020-07-18 08:37:21 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received {'type': 'spotcast/devices', 'id': 4891}
2020-07-18 08:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received invalid command: spotcast/devices
2020-07-18 08:37:21 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received {'type': 'spotcast/devices', 'id': 4892}
2020-07-18 08:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received invalid command: spotcast/devices
2020-07-18 08:37:21 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received {'type': 'spotcast/devices', 'id': 4893}
2020-07-18 08:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140010926862416] Received invalid command: spotcast/devices
`

**Comment by fondberg** [comment]
Seems you have an old version of spotcast

**Comment by davidrustingha** [comment]
The updates fixed the problem for me! Thanks!
